import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";


export const metadata: Metadata = {
  title: "Class assignment 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body>
        <div className="container">
          <Header/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
