import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// importing components
import Top_header from "@/components/Header/Top-header";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Exclusive | Explore No.1 Best Selling Products All Over The Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body>
        <div className="main-container">
        <Top_header/>
        {/* <Header/> */}
        {children}
        </div>
      </body>
    </html>
  );
}
